# This is a basic workflow to help you get started with Actions

name: CI on Main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NAME: ${{ secrets.NAME }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: .env

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: cd simple && yarn test
        env:
          NAME: ${{ secrets.NAME }}

      - name: Build
        run: cd simple && yarn build
